[project]
name = "remote-inference"
version = "0.1.0"
description = "Remote inference package"
requires-python = ">=3.7"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-multipart",  # for file uploads
    "pydantic>=2.0",
    "python-dotenv",
    "requests",
    # Core ML dependencies
    "torch",
    "torchvision",
    "numpy<2",
    "transformers",
    # Image processing
    "opencv-python",
    "pillow",
    # ML libraries
    "timm",
    "scipy",
    "scikit-image",
    "kornia",
    "einops",
    # ML infrastructure
    "huggingface-hub>0.25",
    "accelerate",
    # Utils
    "tqdm",
    "prettytable",
    # Existing dependencies
    "open-clip-torch"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
remote-inference = "remote_inference.cli:main"