[project]
name = "remote-inference"
version = "0.1.0"
description = "Remote inference package"
requires-python = ">=3.7"
dependencies = [
    # Add dependencies here
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"